# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'
    - task: CmdLine@2
      displayName: 'npm install Main'
      inputs:
        script: "npm install    \n"
    - task: CmdLine@2
      displayName: 'npm install and build client'
      inputs:
        script: |
          npm install
          npm run build
          find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +
        workingDirectory: client
    - task: DeleteFiles@1
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/client/node_modules'
        Contents: '*'
        RemoveSourceFolder: true
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'MAIC - TEK Experts CR - v-gengon Group#2 (bddf3c59-769c-49a7-a515-6310ce264e6a)'
        appType: 'webApp'
        appName: 'jesumeNodeDevOpsExpress'
        deployToSlotOrASE: true
        resourceGroupName: 'jesume-testing-webapps'
        slotName: 'test'
        package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
        customWebConfig: '-Handler iisnode -NodeStartFile server.js -appType node'
        deploymentMethod: 'zipDeploy'